### ISSUE TITLE
potential leaflet

### ISSUE THREAD

**Issue by khondula** [SESYNC-ci/geospatial-packages-in-R-lesson#1]
some simple leaflet maps using the existing objects in this lesson. note that sf objects need to be converted to sp type objects `as(x, "Spatial")` before they can go in leaflet which could be clunky 

`
library(rgdal)
library(sf)
library(leaflet)
library(dplyr)
library(raster)

# sesync coords
coords <- c(-76.503394, 38.976546)

# leaflet with a point
leaflet(coords) %>%
  addTiles() %>%
  addMarkers(lng = coords[1], lat = coords[2])

# add a popup at point
leaflet(coords) %>%
  addTiles() %>%
  addMarkers(lng = coords[1], lat = coords[2], popup = "I am here!")

# add layers control with the group argument
# and the layers control layer
leaflet(coords) %>%
  addTiles() %>%
  addMarkers(lng = coords[1], lat = coords[2], 
             popup = "I am here!", group = "point") %>%
  addLayersControl(overlayGroups = c("point"))

# read in the raster
nlcd <- raster("data/nlcd_agg.grd")

leaflet(coords) %>%
  addTiles() %>%
  addMarkers(lng = coords[1], lat = coords[2], popup = "I am here!") %>%
  addRasterImage(nlcd, maxBytes = 15e6)

shp <- 'data/cb_2016_us_county_5m'
counties <- st_read(shp, stringsAsFactors = FALSE)
counties_md <- filter(counties, STATEFP == '24')

# sf need to be made as spatial before plotting in leaflet

leaflet(coords) %>%
  addTiles() %>%
  addMarkers(lng = coords[1], lat = coords[2], popup = "I am here!") %>%
  addPolygons(data = as(counties_md, "Spatial"))
`

**Comment by qdread** [comment]
I think this issue is basically out of date at this point. Will consider "replacing" leaflet part with mapview, see #7
