### ISSUE TITLE
suggestions for time series extraction

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/geospatial-packages-in-R-lesson#2]
[ ] include a raster stack and use raster::extract to generate a time series of one or several points.
[ ] use raster::animate to show a map animation (can leaflet do this, to keep redundency down?)

See example 2 in code from https://github.com/bparment1/workshops_courses_spatial_analyses

**Comment by qdread** [comment]
I think this is too much for the intro lesson and is pretty well covered in the [raster timeseries lesson](https://cyberhelp.sesync.org/raster-time-series-alaska-lesson) that developed out of the example 2 Ian mentioned above. Closing
